### ISSUE TITLE
api doc link fail

### ISSUE THREAD

**Issue by tigercosmos** [ShenTengTu/node-tw-e-invoice#3]
https://shentengtu.github.io/node-tw-e-invoice/modules/_index_.html

**Comment by ShenTengTu** [comment]
The API Doc link :  https://shentengtu.github.io/node-tw-e-invoice/

**Comment by tigercosmos** [comment]
readme 要更新

**Comment by ShenTengTu** [comment]
readme連結沒問題。
我把網址額外加在下面。

**Comment by ShenTengTu** [comment]
喔，是API DOC 內index連結問題，我修改一下

**Comment by ShenTengTu** [comment]
> @tigercosmos
> https://shentengtu.github.io/node-tw-e-invoice/modules/_index_.html

沒加.nojekyll就失效了，已修正，謝謝。
